package top.xfunny.mod;

import org.mtr.mapping.holder.Identifier;
import org.mtr.mapping.registry.BlockEntityTypeRegistryObject;
import top.xfunny.mod.block.*;

public class BlockEntityTypes {

    public static final BlockEntityTypeRegistryObject<TestLiftButtons.BlockEntity> TEST_LIFT_BUTTONS;
    public static final BlockEntityTypeRegistryObject<TestLiftHallLanterns.BlockEntity> TEST_LIFT_HALL_LANTERNS;
    public static final BlockEntityTypeRegistryObject<TestLiftButtonsWithoutScreen.BlockEntity> TEST_LIFT_BUTTONS_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<TestLiftPanel.BlockEntity> TEST_LIFT_PANEL;
    public static final BlockEntityTypeRegistryObject<TestLiftDestinationDispatchTerminal.BlockEntity> TEST_LIFT_DESTINATION_DISPATCH_TERMINAL;
    public static final BlockEntityTypeRegistryObject<CESScreen1Odd.BlockEntity> CES_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<CESScreen1Even.BlockEntity> CES_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<DewhurstUS89Button1.BlockEntity> DEWHURST_US89_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<DewhurstUS91Button1.BlockEntity> DEWHURST_US91_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<DewhurstUS91Button1Braille.BlockEntity> DEWHURST_US91_BUTTON_1_BRAILLE;

    public static final BlockEntityTypeRegistryObject<HitachiVIB320Button.BlockEntity> HITACHI_VIB320_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB320ButtonDotMatrix.BlockEntity> HITACHI_VIB320_BUTTON_DOT_MATRIX;
    public static final BlockEntityTypeRegistryObject<HitachiVIB320ButtonHIP43.BlockEntity> HITACHI_VIB320_BUTTON_HIP43;
    public static final BlockEntityTypeRegistryObject<HitachiVIB322Button.BlockEntity> HITACHI_VIB322_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB322ButtonDotMatrix.BlockEntity> HITACHI_VIB322_BUTTON_DOT_MATRIX;
    public static final BlockEntityTypeRegistryObject<HitachiVIB325Button.BlockEntity> HITACHI_VIB325_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB325ButtonDotMatrix.BlockEntity> HITACHI_VIB325_BUTTON_DOT_MATRIX;
    public static final BlockEntityTypeRegistryObject<HitachiVIB221Button.BlockEntity> HITACHI_VIB221_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB221ButtonDotMatrix.BlockEntity> HITACHI_VIB221_BUTTON_DOT_MATRIX;
    public static final BlockEntityTypeRegistryObject<HitachiVIB221ButtonLCDSegmented.BlockEntity> HITACHI_VIB221_BUTTON_LCD_SEGMENTED;
    public static final BlockEntityTypeRegistryObject<HitachiVIB221ButtonHIP43.BlockEntity> HITACHI_VIB221_BUTTON_HIP43;
    public static final BlockEntityTypeRegistryObject<HitachiVIB820Button.BlockEntity> HITACHI_VIB820_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB820ButtonLCD.BlockEntity> HITACHI_VIB820_BUTTON_LCD;
    public static final BlockEntityTypeRegistryObject<HitachiVIB68Button.BlockEntity> HITACHI_VIB68_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB191Button.BlockEntity> HITACHI_VIB191_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB192Button.BlockEntity> HITACHI_VIB192_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHB820Button.BlockEntity> HITACHI_HB820_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHSB820Button.BlockEntity> HITACHI_HSB820_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiGHL820Lantern1Even.BlockEntity> HITACHI_GHL820_LANTERN_EVEN;
    public static final BlockEntityTypeRegistryObject<HitachiGHL820Lantern1Odd.BlockEntity> HITACHI_GHL820_LANTERN_ODD;
    public static final BlockEntityTypeRegistryObject<HitachiGHL668Lantern1Even.BlockEntity> HITACHI_GHL668_LANTERN_EVEN;
    public static final BlockEntityTypeRegistryObject<HitachiGHL668Lantern1Odd.BlockEntity> HITACHI_GHL668_LANTERN_ODD;
    public static final BlockEntityTypeRegistryObject<HitachiGHL673Lantern1Even.BlockEntity> HITACHI_GHL673_LANTERN_EVEN;
    public static final BlockEntityTypeRegistryObject<HitachiGHL673Lantern1Odd.BlockEntity> HITACHI_GHL673_LANTERN_ODD;
    public static final BlockEntityTypeRegistryObject<HitachiGHI675Screen1Even.BlockEntity> HITACHI_GHI675_SCREEN_EVEN;
    public static final BlockEntityTypeRegistryObject<HitachiGHI675Screen1Odd.BlockEntity> HITACHI_GHI675_SCREEN_ODD;
    public static final BlockEntityTypeRegistryObject<HitachiVIB820proButton.BlockEntity> HITACHI_VIB820PRO_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHSB820proButton.BlockEntity> HITACHI_HSB820PRO_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiGHD820proScreen1Even.BlockEntity> HITACHI_GHD820PRO_SCREEN_EVEN;
    public static final BlockEntityTypeRegistryObject<HitachiGHD820proScreen1Odd.BlockEntity> HITACHI_GHD820PRO_SCREEN_ODD;
    public static final BlockEntityTypeRegistryObject<HitachiVIB628Button.BlockEntity> HITACHI_VIB628_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHB628Button.BlockEntity> HITACHI_HB628_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB668Button.BlockEntity> HITACHI_VIB668_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB658Button.BlockEntity> HITACHI_VIB658_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHB658Button.BlockEntity> HITACHI_HB658_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB663Button.BlockEntity> HITACHI_VIB663_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB681Button.BlockEntity> HITACHI_VIB681_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB676Button.BlockEntity> HITACHI_VIB676_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB679Button.BlockEntity> HITACHI_VIB679_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB673Button.BlockEntity> HITACHI_VIB673_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB673ButtonHIP43.BlockEntity> HITACHI_VIB673_BUTTON_HIP43;
    public static final BlockEntityTypeRegistryObject<HitachiHB673Button.BlockEntity> HITACHI_HB673_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB181AButton.BlockEntity> HITACHI_VIB181A_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiVIB182AButton.BlockEntity> HITACHI_VIB182A_BUTTON;
    public static final BlockEntityTypeRegistryObject<HitachiHB181AButton.BlockEntity> HITACHI_HB181A_BUTTON;

    public static final BlockEntityTypeRegistryObject<KoneKDS330Button1.BlockEntity> KONE_KDS330_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<KoneKDS330Button1WithoutScreen.BlockEntity> KONE_KDS330_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<KoneKDS330Lantern1.BlockEntity> KONE_KDS330_LANTERN_1;
    public static final BlockEntityTypeRegistryObject<KoneKSS280Button1.BlockEntity> KONE_KSS280_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<KoneKSS280Button1WithoutScreen.BlockEntity> KONE_KSS280_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<KoneKSS280Screen1Odd.BlockEntity> KONE_KSS280_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<KoneKSS280Screen1Even.BlockEntity> KONE_KSS280_SCREEN_1_EVEN;

    public static final BlockEntityTypeRegistryObject<KoneMButton1.BlockEntity> KONE_M_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<KoneMButton2.BlockEntity> KONE_M_BUTTON_2;
    public static final BlockEntityTypeRegistryObject<KoneMScreen1Odd.BlockEntity> KONE_M_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<KoneMScreen1Even.BlockEntity> KONE_M_SCREEN_1_EVEN;

    public static final BlockEntityTypeRegistryObject<MitsubishiGPSButton1.BlockEntity> MITSUBISHI_GPS_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPSButton1WithoutScreen.BlockEntity> MITSUBISHI_GPS_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiButtonShunHingSquare.BlockEntity> MITSUBISHI_BUTTON_SHUN_HING_SQUARE;
    public static final BlockEntityTypeRegistryObject<MitsubishiRyodenScreen1Even.BlockEntity> MITSUBISHI_RYODEN_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiRyodenScreen1Odd.BlockEntity> MITSUBISHI_RYODEN_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiRyodenScreen2Even.BlockEntity> MITSUBISHI_RYODEN_SCREEN_2_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiRyodenScreen2Odd.BlockEntity> MITSUBISHI_RYODEN_SCREEN_2_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Button1.BlockEntity> MITSUBISHI_GPS3_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Button1WithoutScreen.BlockEntity> MITSUBISHI_GPS3_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Button2.BlockEntity> MITSUBISHI_GPS3_BUTTON_2;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Button2WithoutScreen.BlockEntity> MITSUBISHI_GPS3_BUTTON_2_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Screen1Even.BlockEntity> MITSUBISHI_GPS3_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiGPS3Screen1Odd.BlockEntity> MITSUBISHI_GPS3_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton1.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton1Segmented.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_1_SEGMENTED;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton1WithoutScreen.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton2.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_2;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton2Segmented.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_2_SEGMENTED;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton2LCD1.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_2_LCD_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton2WithoutScreen.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_2_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton3.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_3;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton3Segmented.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_3_SEGMENTED;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton3WithoutScreen.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_3_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton4.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_4;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton4WithoutScreen.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_4_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton5.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_5;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayButton5WithoutScreen.BlockEntity> MITSUBISHI_NEXWAY_BUTTON_5_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiButtonSHT.BlockEntity> MITSUBISHI_BUTTON_SHT;
    public static final BlockEntityTypeRegistryObject<MitsubishiMaxiezButton1Gold.BlockEntity> MITSUBISHI_MAXIEZ_BUTTON_1_GOLD;
    public static final BlockEntityTypeRegistryObject<MitsubishiMaxiezButton1Silver.BlockEntity> MITSUBISHI_MAXIEZ_BUTTON_1_SILVER;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayLantern1HorizontalEven.BlockEntity> MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayLantern1HorizontalOdd.BlockEntity> MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayLantern1VerticalEven.BlockEntity> MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayLantern1VerticalOdd.BlockEntity> MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen1Even.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen1Odd.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen1SegmentedEven.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen1SegmentedOdd.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen2Even.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_2_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen2Odd.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_2_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen3Even.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_3_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen3Odd.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_3_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen3SegmentedEven.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_EVEN;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayScreen3SegmentedOdd.BlockEntity> MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiMPVFButton1.BlockEntity> MITSUBISHI_MPVF_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiMPVFScreen1VerticalOdd.BlockEntity> MITSUBISHI_MPVF_SCREEN_1_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<MitsubishiMPVFScreen1VerticalEven.BlockEntity> MITSUBISHI_MPVF_SCREEN_1_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiNexWayCRButton1.BlockEntity> SHANGHAI_MITSUBISHI_NEXWAY_CR_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Button1.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Button1WithoutScreen.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Button2.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_2;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Button3LCD.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_3_LCD;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Screen1Even.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Screen1Odd.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Screen1WideEven.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_EVEN;
    public static final BlockEntityTypeRegistryObject<ShanghaiMitsubishiLehy3Screen1WideOdd.BlockEntity> SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_ODD;

    public static final BlockEntityTypeRegistryObject<OtisSeries1Button.BlockEntity> OTIS_SERIES_1_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<OtisSeries1Button.BlockEntity> OTIS_SERIES_1_BUTTON_2;
    public static final BlockEntityTypeRegistryObject<OtisSeries1Screen.BlockEntity> OTIS_SERIES_1_SCREEN_1;
    public static final BlockEntityTypeRegistryObject<OtisSeries1Lantern1Even.BlockEntity> OTIS_SERIES_1_LANTERN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<OtisSeries1Lantern1Odd.BlockEntity> OTIS_SERIES_1_LANTERN_1_ODD;
    public static final BlockEntityTypeRegistryObject<OtisSeries1LanternScreen1Even.BlockEntity> OTIS_SERIES_1_LANTERN_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<OtisSeries1LanternScreen1Odd.BlockEntity> OTIS_SERIES_1_LANTERN_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<OtisSeries3Button1.BlockEntity> OTIS_SERIES_3_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<OtisSeries3Screen1Odd.BlockEntity> OTIS_SERIES_3_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<OtisSeries3Screen1Even.BlockEntity> OTIS_SERIES_3_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<OtisSeries3ELDScreen1Odd.BlockEntity> OTIS_SERIES_3_ELD_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<OtisSeries3ELDScreen1Even.BlockEntity> OTIS_SERIES_3_ELD_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<OtisSeries3Lantern1ArrowOdd.BlockEntity> OTIS_SERIES_3_LANTERN_1_ARROW_ODD;
    public static final BlockEntityTypeRegistryObject<OtisSeries3Lantern1ArrowEven.BlockEntity> OTIS_SERIES_3_LANTERN_1_ARROW_EVEN;
    public static final BlockEntityTypeRegistryObject<OtisSPEC60Button1.BlockEntity> OTIS_SPEC_60_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<OtisSPEC90Button1Black.BlockEntity> OTIS_SPEC_90_BUTTON_1_BLACK;
    public static final BlockEntityTypeRegistryObject<OtisSPEC90Button1White.BlockEntity> OTIS_SPEC_90_BUTTON_1_WHITE;
    public static final BlockEntityTypeRegistryObject<OtisSPEC90Button2Black.BlockEntity> OTIS_SPEC_90_BUTTON_2_BLACK;
    public static final BlockEntityTypeRegistryObject<OtisSPEC90Button2White.BlockEntity> OTIS_SPEC_90_BUTTON_2_WHITE;

    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesD2Button.BlockEntity> SCHINDLER_D_SERIES_D2BUTTON;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen1Odd.BlockEntity> SCHINDLER_D_SERIES_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen1Even.BlockEntity> SCHINDLER_D_SERIES_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2GreenOdd.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_GREEN_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2GreenEven.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_GREEN_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2BlueOdd.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_BLUE_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2BlueEven.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_BLUE_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2RedOdd.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_RED_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerDSeriesScreen2RedEven.BlockEntity> SCHINDLER_D_SERIES_SCREEN_2_RED_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerZLine3Keypad1.BlockEntity> SCHINDLER_Z_LINE_3_KEYPAD_1;

    public static final BlockEntityTypeRegistryObject<ThyssenkruppTEGL1Button1.BlockEntity> THYSSENKRUPP_TEGL1_BUTTON_1;

    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesButton.BlockEntity> SCHINDLER_M_SERIES_BUTTON;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesTouchButton.BlockEntity> SCHINDLER_M_SERIES_TOUCH_BUTTON;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesRoundTouchButton.BlockEntity> SCHINDLER_M_SERIES_ROUND_TOUCH_BUTTON;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesRoundLantern1Even.BlockEntity> SCHINDLER_M_SERIES_ROUND_LANTERN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesRoundLantern1Odd.BlockEntity> SCHINDLER_M_SERIES_ROUND_LANTERN_1_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen1.BlockEntity> SCHINDLER_M_SERIES_SCREEN_1;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen2Odd.BlockEntity> SCHINDLER_M_SERIES_SCREEN_2_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen2Even.BlockEntity> SCHINDLER_M_SERIES_SCREEN_2_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen3Odd.BlockEntity> SCHINDLER_M_SERIES_SCREEN_3_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen3Even.BlockEntity> SCHINDLER_M_SERIES_SCREEN_3_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen4Odd.BlockEntity> SCHINDLER_M_SERIES_SCREEN_4_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerMSeriesScreen4Even.BlockEntity> SCHINDLER_M_SERIES_SCREEN_4_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerSSeriesGreyButton.BlockEntity> SCHINDLER_S_SERIES_GREY_BUTTON;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton1White.BlockEntity> SCHINDLER_LINEA_BUTTON_1_WHITE;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton1WhiteWithoutScreen.BlockEntity> SCHINDLER_LINEA_BUTTON_1_WHITE_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton1Black.BlockEntity> SCHINDLER_LINEA_BUTTON_1_BLACK;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton1BlackWithoutScreen.BlockEntity> SCHINDLER_LINEA_BUTTON_1_BLACK_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton2White.BlockEntity> SCHINDLER_LINEA_BUTTON_2_WHITE;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton2WhiteWithoutScreen.BlockEntity> SCHINDLER_LINEA_BUTTON_2_WHITE_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton2Black.BlockEntity> SCHINDLER_LINEA_BUTTON_2_BLACK;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaButton2BlackWithoutScreen.BlockEntity> SCHINDLER_LINEA_BUTTON_2_BLACK_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1WhiteHorizontalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1WhiteHorizontalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1WhiteVerticalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1WhiteVerticalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1BlackHorizontalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1BlackHorizontalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1BlackVerticalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen1BlackVerticalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2WhiteHorizontalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2WhiteHorizontalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2WhiteVerticalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2WhiteVerticalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2BlackHorizontalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2BlackHorizontalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2BlackVerticalEven.BlockEntity> SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerLineaScreen2BlackVerticalOdd.BlockEntity> SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSButton1.BlockEntity> SCHINDLER_FI_GS_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSTouchButton1.BlockEntity> SCHINDLER_FI_GS_TOUCH_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSTouchButton1WithoutScreen.BlockEntity> SCHINDLER_FI_GS_TOUCH_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSButton1Steel.BlockEntity> SCHINDLER_FI_GS_BUTTON_1_STEEL;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1SteelOdd.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_STEEL_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1SteelEven.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_STEEL_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1BlackOdd.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_BLACK_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1BlackEven.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_BLACK_EVEN;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1GreyOdd.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_GREY_ODD;
    public static final BlockEntityTypeRegistryObject<SchindlerFIGSScreen1GreyEven.BlockEntity> SCHINDLER_FI_GS_SCREEN_1_GREY_EVEN;

    public static final BlockEntityTypeRegistryObject<HitachiB85Button1.BlockEntity> HITACHI_B85_BUTTON_1;
    public static final BlockEntityTypeRegistryObject<HitachiB85Button1WithoutScreen.BlockEntity> HITACHI_B85_BUTTON_1_WITHOUT_SCREEN;
    public static final BlockEntityTypeRegistryObject<HitachiB85Button2.BlockEntity> HITACHI_B85_BUTTON_2;

    public static final BlockEntityTypeRegistryObject<HitachiButtonPAFC.BlockEntity> HITACHI_BUTTON_PAFC;

    public static final BlockEntityTypeRegistryObject<TonicDSScreen1Odd.BlockEntity> TONIC_DS_SCREEN_1_ODD;
    public static final BlockEntityTypeRegistryObject<TonicDSScreen1Even.BlockEntity> TONIC_DS_SCREEN_1_EVEN;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1RedOdd.BlockEntity> TONIC_DM_SCREEN_1_RED_ODD;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1RedEven.BlockEntity> TONIC_DM_SCREEN_1_RED_EVEN;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1GreenOdd.BlockEntity> TONIC_DM_SCREEN_1_GREEN_ODD;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1GreenEven.BlockEntity> TONIC_DM_SCREEN_1_GREEN_EVEN;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1YellowOdd.BlockEntity> TONIC_DM_SCREEN_1_YELLOW_ODD;
    public static final BlockEntityTypeRegistryObject<TonicDMScreen1YellowEven.BlockEntity> TONIC_DM_SCREEN_1_YELLOW_EVEN;


    public static final BlockEntityTypeRegistryObject<HitachiB85Door1.BlockEntity> HITACHI_B85_DOOR_1;
    public static final BlockEntityTypeRegistryObject<KoneMDoor1.BlockEntity> KONE_M_DOOR_1;
    public static final BlockEntityTypeRegistryObject<MitsubishiNexWayDoor1.BlockEntity> MITSUBISHI_NEXWAY_DOOR_1;
    public static final BlockEntityTypeRegistryObject<OtisE411USDoor1.BlockEntity> OTIS_E411_US_DOOR_1;
    public static final BlockEntityTypeRegistryObject<SchindlerQKS9Door1.BlockEntity> SCHINDLER_QKS9_DOOR_1;

    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_2_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_2_ODD;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_3_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_3_ODD;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_4_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_4_ODD;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_5_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_5_ODD;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_6_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_6_ODD;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_7_EVEN;
    public static final BlockEntityTypeRegistryObject<PATRS01RailwaySign.BlockEntity> PAT_RS01_RAILWAY_SIGN_7_ODD;

    public static final BlockEntityTypeRegistryObject<EmptyFloor.BlockEntity> LIFT_TRACK_EMPTY_FLOOR;


    static {
        TEST_LIFT_BUTTONS = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_buttons"), TestLiftButtons.BlockEntity::new, Blocks.TEST_LIFT_BUTTONS::get);
        TEST_LIFT_HALL_LANTERNS = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_hall_lanterns"), TestLiftHallLanterns.BlockEntity::new, Blocks.TEST_LIFT_HALL_LANTERNS::get);
        TEST_LIFT_BUTTONS_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_buttons_without_screen"), TestLiftButtonsWithoutScreen.BlockEntity::new, Blocks.TEST_LIFT_BUTTONS_WITHOUT_SCREEN::get);
        TEST_LIFT_PANEL = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_panel"), TestLiftPanel.BlockEntity::new, Blocks.TEST_LIFT_PANEL::get);
        TEST_LIFT_DESTINATION_DISPATCH_TERMINAL = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_destination_dispatch_terminal"), TestLiftDestinationDispatchTerminal.BlockEntity::new, Blocks.TEST_LIFT_DESTINATION_DISPATCH_TERMINAL::get);

        CES_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "ces_screen_1_odd"), CESScreen1Odd.BlockEntity::new, Blocks.CES_SCREEN_1_ODD::get);
        CES_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "ces_screen_1_even"), CESScreen1Even.BlockEntity::new, Blocks.CES_SCREEN_1_EVEN::get);

        DEWHURST_US89_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "dewhurst_us89_button_1"), DewhurstUS89Button1.BlockEntity::new, Blocks.DEWHURST_US89_BUTTON_1::get);
        DEWHURST_US91_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "dewhurst_us91_button_1"), DewhurstUS91Button1.BlockEntity::new, Blocks.DEWHURST_US91_BUTTON_1::get);
        DEWHURST_US91_BUTTON_1_BRAILLE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "dewhurst_us91_button_1_braille"), DewhurstUS91Button1Braille.BlockEntity::new, Blocks.DEWHURST_US91_BUTTON_1_BRAILLE::get);
        KONE_KDS330_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kds330_surface_button_1"), KoneKDS330Button1.BlockEntity::new, Blocks.KONE_KDS330_BUTTON_1::get);
        KONE_KDS330_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kds330_surface_button_1_without_screen"), KoneKDS330Button1WithoutScreen.BlockEntity::new, Blocks.KONE_KDS330_BUTTON_1_WITHOUT_SCREEN::get);
        KONE_KDS330_LANTERN_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kds330_surface_lantern_1"), KoneKDS330Lantern1.BlockEntity::new, Blocks.KONE_KDS330_LANTERN_1::get);
        KONE_KSS280_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kss280_surface_button_1"), KoneKSS280Button1.BlockEntity::new, Blocks.KONE_KSS280_BUTTON_1::get);
        KONE_KSS280_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kss280_surface_button_1_without_screen"), KoneKSS280Button1WithoutScreen.BlockEntity::new, Blocks.KONE_KSS280_BUTTON_1_WITHOUT_SCREEN::get);
        KONE_KSS280_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kss280_surface_screen_1_odd"), KoneKSS280Screen1Odd.BlockEntity::new, Blocks.KONE_KSS280_SCREEN_1_ODD::get);
        KONE_KSS280_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_kss280_surface_screen_1_even"), KoneKSS280Screen1Even.BlockEntity::new, Blocks.KONE_KSS280_SCREEN_1_EVEN::get);
        KONE_M_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_m_button_1"), KoneMButton1.BlockEntity::new, Blocks.KONE_M_BUTTON_1::get);
        KONE_M_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_m_button_2"), KoneMButton2.BlockEntity::new, Blocks.KONE_M_BUTTON_2::get);
        KONE_M_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_m_screen_1_odd"), KoneMScreen1Odd.BlockEntity::new, Blocks.KONE_M_SCREEN_1_ODD::get);
        KONE_M_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_m_screen_1_even"), KoneMScreen1Even.BlockEntity::new, Blocks.KONE_M_SCREEN_1_EVEN::get);
        MITSUBISHI_GPS_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps_button_1"), MitsubishiGPSButton1.BlockEntity::new, Blocks.MITSUBISHI_GPS_BUTTON_1::get);
        MITSUBISHI_GPS_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps_button_1_without_screen"), MitsubishiGPSButton1WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_GPS_BUTTON_1_WITHOUT_SCREEN::get);
        MITSUBISHI_BUTTON_SHUN_HING_SQUARE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_button_shun_hing_square"), MitsubishiButtonShunHingSquare.BlockEntity::new, Blocks.MITSUBISHI_BUTTON_SHUN_HING_SQUARE::get);
        MITSUBISHI_GPS3_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_button_1"), MitsubishiGPS3Button1.BlockEntity::new, Blocks.MITSUBISHI_GPS3_BUTTON_1::get);
        MITSUBISHI_GPS3_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_button_1_without_screen"), MitsubishiGPS3Button1WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_GPS3_BUTTON_1_WITHOUT_SCREEN::get);
        MITSUBISHI_GPS3_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_button_2"), MitsubishiGPS3Button2.BlockEntity::new, Blocks.MITSUBISHI_GPS3_BUTTON_2::get);
        MITSUBISHI_GPS3_BUTTON_2_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_button_2_without_screen"), MitsubishiGPS3Button2WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_GPS3_BUTTON_2_WITHOUT_SCREEN::get);
        MITSUBISHI_GPS3_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_screen_1_even"), MitsubishiGPS3Screen1Even.BlockEntity::new, Blocks.MITSUBISHI_GPS3_SCREEN_1_EVEN::get);
        MITSUBISHI_GPS3_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_gps3_screen_1_odd"), MitsubishiGPS3Screen1Odd.BlockEntity::new, Blocks.MITSUBISHI_GPS3_SCREEN_1_ODD::get);
        MITSUBISHI_RYODEN_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_ryoden_screen_1_even"), MitsubishiRyodenScreen1Even.BlockEntity::new, Blocks.MITSUBISHI_RYODEN_SCREEN_1_EVEN::get);
        MITSUBISHI_RYODEN_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_ryoden_screen_1_odd"), MitsubishiRyodenScreen1Odd.BlockEntity::new, Blocks.MITSUBISHI_RYODEN_SCREEN_1_ODD::get);
        MITSUBISHI_RYODEN_SCREEN_2_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_ryoden_screen_2_even"), MitsubishiRyodenScreen2Even.BlockEntity::new, Blocks.MITSUBISHI_RYODEN_SCREEN_2_EVEN::get);
        MITSUBISHI_RYODEN_SCREEN_2_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_ryoden_screen_2_odd"), MitsubishiRyodenScreen2Odd.BlockEntity::new, Blocks.MITSUBISHI_RYODEN_SCREEN_2_ODD::get);
        MITSUBISHI_NEXWAY_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_1"), MitsubishiNexWayButton1.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_1::get);
        MITSUBISHI_NEXWAY_BUTTON_1_SEGMENTED = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_1_segmented"), MitsubishiNexWayButton1Segmented.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_1_SEGMENTED::get);
        MITSUBISHI_NEXWAY_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_1_without_screen"), MitsubishiNexWayButton1WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_1_WITHOUT_SCREEN::get);
        MITSUBISHI_NEXWAY_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_2"), MitsubishiNexWayButton2.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_2::get);
        MITSUBISHI_NEXWAY_BUTTON_2_SEGMENTED = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_2_segmented"), MitsubishiNexWayButton2Segmented.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_2_SEGMENTED::get);
        MITSUBISHI_NEXWAY_BUTTON_2_LCD_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_2_lcd_1"), MitsubishiNexWayButton2LCD1.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_2_LCD_1::get);
        MITSUBISHI_NEXWAY_BUTTON_2_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_2_without_screen"), MitsubishiNexWayButton2WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_2_WITHOUT_SCREEN::get);
        MITSUBISHI_NEXWAY_BUTTON_3 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_3"), MitsubishiNexWayButton3.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_3::get);
        MITSUBISHI_NEXWAY_BUTTON_3_SEGMENTED = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_3_segmented"), MitsubishiNexWayButton3Segmented.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_3_SEGMENTED::get);
        MITSUBISHI_NEXWAY_BUTTON_3_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_3_without_screen"), MitsubishiNexWayButton3WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_3_WITHOUT_SCREEN::get);
        MITSUBISHI_NEXWAY_BUTTON_4 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_4"), MitsubishiNexWayButton4.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_4::get);
        MITSUBISHI_NEXWAY_BUTTON_4_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_4_without_screen"), MitsubishiNexWayButton4WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_4_WITHOUT_SCREEN::get);
        MITSUBISHI_NEXWAY_BUTTON_5 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_5"), MitsubishiNexWayButton5.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_5::get);
        MITSUBISHI_NEXWAY_BUTTON_5_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_button_5_without_screen"), MitsubishiNexWayButton5WithoutScreen.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_BUTTON_5_WITHOUT_SCREEN::get);
        MITSUBISHI_BUTTON_SHT = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_button_sht"), MitsubishiButtonSHT.BlockEntity::new, Blocks.MITSUBISHI_BUTTON_SHT::get);
        MITSUBISHI_MAXIEZ_BUTTON_1_GOLD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_maxiez_button_1_gold"), MitsubishiMaxiezButton1Gold.BlockEntity::new, Blocks.MITSUBISHI_MAXIEZ_BUTTON_1_GOLD::get);
        MITSUBISHI_MAXIEZ_BUTTON_1_SILVER = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_maxiez_button_1_silver"), MitsubishiMaxiezButton1Silver.BlockEntity::new, Blocks.MITSUBISHI_MAXIEZ_BUTTON_1_SILVER::get);
        MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_lantern_1_horizontal_even"), MitsubishiNexWayLantern1HorizontalEven.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_EVEN::get);
        MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_lantern_1_horizontal_odd"), MitsubishiNexWayLantern1HorizontalOdd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_LANTERN_1_HORIZONTAL_ODD::get);
        MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_lantern_1_vertical_even"), MitsubishiNexWayLantern1VerticalEven.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_EVEN::get);
        MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_lantern_1_vertical_odd"), MitsubishiNexWayLantern1VerticalOdd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_LANTERN_1_VERTICAL_ODD::get);
        MITSUBISHI_NEXWAY_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_1_even"), MitsubishiNexWayScreen1Even.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_1_EVEN::get);
        MITSUBISHI_NEXWAY_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_1_odd"), MitsubishiNexWayScreen1Odd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_1_ODD::get);
        MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_1_segmented_even"), MitsubishiNexWayScreen1SegmentedEven.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_EVEN::get);
        MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_1_segmented_odd"), MitsubishiNexWayScreen1SegmentedOdd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_1_SEGMENTED_ODD::get);
        MITSUBISHI_NEXWAY_SCREEN_2_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_2_even"), MitsubishiNexWayScreen2Even.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_2_EVEN::get);
        MITSUBISHI_NEXWAY_SCREEN_2_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_2_odd"), MitsubishiNexWayScreen2Odd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_2_ODD::get);
        MITSUBISHI_NEXWAY_SCREEN_3_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_3_even"), MitsubishiNexWayScreen3Even.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_3_EVEN::get);
        MITSUBISHI_NEXWAY_SCREEN_3_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_3_odd"), MitsubishiNexWayScreen3Odd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_3_ODD::get);
        MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_3_segmented_even"), MitsubishiNexWayScreen3SegmentedEven.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_EVEN::get);
        MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_screen_3_segmented_odd"), MitsubishiNexWayScreen3SegmentedOdd.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_SCREEN_3_SEGMENTED_ODD::get);
        MITSUBISHI_MPVF_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_mpvf_button_1"), MitsubishiMPVFButton1.BlockEntity::new, Blocks.MITSUBISHI_MPVF_BUTTON_1::get);
        MITSUBISHI_MPVF_SCREEN_1_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_mpvf_screen_1_vertical_odd"), MitsubishiMPVFScreen1VerticalOdd.BlockEntity::new, Blocks.MITSUBISHI_MPVF_SCREEN_1_VERTICAL_ODD::get);
        MITSUBISHI_MPVF_SCREEN_1_VERTICAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_mpvf_screen_1_vertical_even"), MitsubishiMPVFScreen1VerticalEven.BlockEntity::new, Blocks.MITSUBISHI_MPVF_SCREEN_1_VERTICAL_EVEN::get);
        SHANGHAI_MITSUBISHI_NEXWAY_CR_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_nexway_cr_button_1"), ShanghaiMitsubishiNexWayCRButton1.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_NEXWAY_CR_BUTTON_1::get);
        SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_button_1"), ShanghaiMitsubishiLehy3Button1.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1::get);
        SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_button_1_without_screen"), ShanghaiMitsubishiLehy3Button1WithoutScreen.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_1_WITHOUT_SCREEN::get);
        SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_button_2"), ShanghaiMitsubishiLehy3Button2.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_2::get);
        SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_3_LCD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_button_3_lcd"), ShanghaiMitsubishiLehy3Button3LCD.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_BUTTON_3_LCD::get);
        SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_screen_1_even"), ShanghaiMitsubishiLehy3Screen1Even.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_EVEN::get);
        SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_screen_1_odd"), ShanghaiMitsubishiLehy3Screen1Odd.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_ODD::get);
        SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_screen_1_wide_even"), ShanghaiMitsubishiLehy3Screen1WideEven.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_EVEN::get);
        SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "shanghai_mitsubishi_lehy_3_screen_1_wide_odd"), ShanghaiMitsubishiLehy3Screen1WideOdd.BlockEntity::new, Blocks.SHANGHAI_MITSUBISHI_LEHY_3_SCREEN_1_WIDE_ODD::get);
        OTIS_SERIES_1_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_button_1"), OtisSeries1Button.BlockEntity::new, Blocks.OTIS_SERIES_1_BUTTON_1::get);
        OTIS_SERIES_1_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_button_2"), OtisSeries1Button.BlockEntity::new, Blocks.OTIS_SERIES_1_BUTTON_2::get);
        OTIS_SERIES_1_SCREEN_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_screen_1"), OtisSeries1Screen.BlockEntity::new, Blocks.OTIS_SERIES_1_SCREEN_1::get);
        OTIS_SERIES_1_LANTERN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_lantern_1_even"), OtisSeries1Lantern1Even.BlockEntity::new, Blocks.OTIS_SERIES_1_LANTERN_1_EVEN::get);
        OTIS_SERIES_1_LANTERN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_lantern_1_odd"), OtisSeries1Lantern1Odd.BlockEntity::new, Blocks.OTIS_SERIES_1_LANTERN_1_ODD::get);
        OTIS_SERIES_1_LANTERN_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_lantern_screen_1_even"), OtisSeries1LanternScreen1Even.BlockEntity::new, Blocks.OTIS_SERIES_1_LANTERN_SCREEN_1_EVEN::get);
        OTIS_SERIES_1_LANTERN_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_1_lantern_screen_1_odd"), OtisSeries1LanternScreen1Odd.BlockEntity::new, Blocks.OTIS_SERIES_1_LANTERN_SCREEN_1_ODD::get);
        OTIS_SERIES_3_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_button_1"), OtisSeries3Button1.BlockEntity::new, Blocks.OTIS_SERIES_3_BUTTON_1::get);
        OTIS_SERIES_3_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_screen_1_odd"), OtisSeries3Screen1Odd.BlockEntity::new, Blocks.OTIS_SERIES_3_SCREEN_1_ODD::get);
        OTIS_SERIES_3_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_screen_1_even"), OtisSeries3Screen1Even.BlockEntity::new, Blocks.OTIS_SERIES_3_SCREEN_1_EVEN::get);
        OTIS_SERIES_3_ELD_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_eld_screen_1_odd"), OtisSeries3ELDScreen1Odd.BlockEntity::new, Blocks.OTIS_SERIES_3_ELD_SCREEN_1_ODD::get);
        OTIS_SERIES_3_ELD_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_eld_screen_1_even"), OtisSeries3ELDScreen1Even.BlockEntity::new, Blocks.OTIS_SERIES_3_ELD_SCREEN_1_EVEN::get);
        OTIS_SERIES_3_LANTERN_1_ARROW_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_lantern_1_arrow_odd"), OtisSeries3Lantern1ArrowOdd.BlockEntity::new, Blocks.OTIS_SERIES_3_LANTERN_1_ARROW_ODD::get);
        OTIS_SERIES_3_LANTERN_1_ARROW_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_series_3_lantern_1_arrow_even"), OtisSeries3Lantern1ArrowEven.BlockEntity::new, Blocks.OTIS_SERIES_3_LANTERN_1_ARROW_EVEN::get);
        OTIS_SPEC_60_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_spec_60_button_1"), OtisSPEC60Button1.BlockEntity::new, Blocks.OTIS_SPEC_60_BUTTON_1::get);
        OTIS_SPEC_90_BUTTON_1_BLACK = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_spec_90_button_1_black"), OtisSPEC90Button1Black.BlockEntity::new, Blocks.OTIS_SPEC_90_BUTTON_1_BLACK::get);
        OTIS_SPEC_90_BUTTON_1_WHITE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_spec_90_button_1_white"), OtisSPEC90Button1White.BlockEntity::new, Blocks.OTIS_SPEC_90_BUTTON_1_WHITE::get);
        OTIS_SPEC_90_BUTTON_2_BLACK = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_spec_90_button_2_black"), OtisSPEC90Button2Black.BlockEntity::new, Blocks.OTIS_SPEC_90_BUTTON_2_BLACK::get);
        OTIS_SPEC_90_BUTTON_2_WHITE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_spec_90_button_2_white"), OtisSPEC90Button2White.BlockEntity::new, Blocks.OTIS_SPEC_90_BUTTON_2_WHITE::get);
        SCHINDLER_D_SERIES_D2BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_d2button.json"), SchindlerDSeriesD2Button.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_D2BUTTON::get);
        SCHINDLER_D_SERIES_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_1_odd"), SchindlerDSeriesScreen1Odd.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_1_ODD::get);
        SCHINDLER_D_SERIES_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_1_even"), SchindlerDSeriesScreen1Even.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_1_EVEN::get);
        SCHINDLER_D_SERIES_SCREEN_2_GREEN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_green_odd"), SchindlerDSeriesScreen2GreenOdd.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_GREEN_ODD::get);
        SCHINDLER_D_SERIES_SCREEN_2_GREEN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_green_even"), SchindlerDSeriesScreen2GreenEven.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_GREEN_EVEN::get);
        SCHINDLER_D_SERIES_SCREEN_2_BLUE_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_blue_odd"), SchindlerDSeriesScreen2BlueOdd.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_BLUE_ODD::get);
        SCHINDLER_D_SERIES_SCREEN_2_BLUE_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_blue_even"), SchindlerDSeriesScreen2BlueEven.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_BLUE_EVEN::get);
        SCHINDLER_D_SERIES_SCREEN_2_RED_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_red_odd"), SchindlerDSeriesScreen2RedOdd.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_RED_ODD::get);
        SCHINDLER_D_SERIES_SCREEN_2_RED_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_d_series_screen_2_red_even"), SchindlerDSeriesScreen2RedEven.BlockEntity::new, Blocks.SCHINDLER_D_SERIES_SCREEN_2_RED_EVEN::get);
        SCHINDLER_M_SERIES_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_button.json"), SchindlerMSeriesButton.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_BUTTON::get);
        SCHINDLER_M_SERIES_TOUCH_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_touch_button.json"), SchindlerMSeriesTouchButton.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_TOUCH_BUTTON::get);
        SCHINDLER_M_SERIES_ROUND_TOUCH_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_round_touch_button.json"), SchindlerMSeriesRoundTouchButton.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_ROUND_TOUCH_BUTTON::get);
        SCHINDLER_M_SERIES_ROUND_LANTERN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_round_lantern_1_odd"), SchindlerMSeriesRoundLantern1Odd.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_ROUND_LANTERN_1_ODD::get);
        SCHINDLER_M_SERIES_ROUND_LANTERN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_round_lantern_1_even"), SchindlerMSeriesRoundLantern1Even.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_ROUND_LANTERN_1_EVEN::get);
        SCHINDLER_M_SERIES_SCREEN_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_1"), SchindlerMSeriesScreen1.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_1::get);
        SCHINDLER_M_SERIES_SCREEN_2_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_2_odd"), SchindlerMSeriesScreen2Odd.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_2_ODD::get);
        SCHINDLER_M_SERIES_SCREEN_2_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_2_even"), SchindlerMSeriesScreen2Even.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_2_EVEN::get);
        SCHINDLER_M_SERIES_SCREEN_3_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_3_odd"), SchindlerMSeriesScreen3Odd.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_3_ODD::get);
        SCHINDLER_M_SERIES_SCREEN_3_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_3_even"), SchindlerMSeriesScreen3Even.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_3_EVEN::get);
        SCHINDLER_M_SERIES_SCREEN_4_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_4_odd"), SchindlerMSeriesScreen4Odd.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_4_ODD::get);
        SCHINDLER_M_SERIES_SCREEN_4_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_m_series_screen_4_even"), SchindlerMSeriesScreen4Even.BlockEntity::new, Blocks.SCHINDLER_M_SERIES_SCREEN_4_EVEN::get);
        SCHINDLER_S_SERIES_GREY_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_s_series_grey_button"), SchindlerSSeriesGreyButton.BlockEntity::new, Blocks.SCHINDLER_S_SERIES_GREY_BUTTON::get);
        SCHINDLER_LINEA_BUTTON_1_WHITE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_1_white"), SchindlerLineaButton1White.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_1_WHITE::get);
        SCHINDLER_LINEA_BUTTON_1_BLACK = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_1_black"), SchindlerLineaButton1Black.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_1_BLACK::get);
        SCHINDLER_LINEA_BUTTON_2_WHITE = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_2_white"), SchindlerLineaButton2White.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_2_WHITE::get);
        SCHINDLER_LINEA_BUTTON_2_BLACK = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_2_black"), SchindlerLineaButton2Black.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_2_BLACK::get);
        SCHINDLER_LINEA_BUTTON_1_WHITE_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_1_white_without_screen"), SchindlerLineaButton1WhiteWithoutScreen.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_1_WHITE_WITHOUT_SCREEN::get);
        SCHINDLER_LINEA_BUTTON_1_BLACK_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_1_black_without_screen"), SchindlerLineaButton1BlackWithoutScreen.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_1_BLACK_WITHOUT_SCREEN::get);
        SCHINDLER_LINEA_BUTTON_2_WHITE_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_2_white_without_screen"), SchindlerLineaButton2WhiteWithoutScreen.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_2_WHITE_WITHOUT_SCREEN::get);
        SCHINDLER_LINEA_BUTTON_2_BLACK_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_button_2_black_without_screen"), SchindlerLineaButton2BlackWithoutScreen.BlockEntity::new, Blocks.SCHINDLER_LINEA_BUTTON_2_BLACK_WITHOUT_SCREEN::get);
        SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_white_horizontal_odd"), SchindlerLineaScreen1WhiteHorizontalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_white_horizontal_even"), SchindlerLineaScreen1WhiteHorizontalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_WHITE_HORIZONTAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_white_vertical_odd"), SchindlerLineaScreen1WhiteVerticalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_white_vertical_even"), SchindlerLineaScreen1WhiteVerticalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_WHITE_VERTICAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_black_horizontal_odd"), SchindlerLineaScreen1BlackHorizontalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_black_horizontal_even"), SchindlerLineaScreen1BlackHorizontalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_BLACK_HORIZONTAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_black_vertical_odd"), SchindlerLineaScreen1BlackVerticalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_EVEN     = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_1_black_vertical_even"), SchindlerLineaScreen1BlackVerticalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_1_BLACK_VERTICAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_white_horizontal_odd"), SchindlerLineaScreen2WhiteHorizontalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_white_horizontal_even"), SchindlerLineaScreen2WhiteHorizontalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_WHITE_HORIZONTAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_white_vertical_odd"), SchindlerLineaScreen2WhiteVerticalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_white_vertical_even"), SchindlerLineaScreen2WhiteVerticalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_WHITE_VERTICAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_black_horizontal_odd"), SchindlerLineaScreen2BlackHorizontalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_black_horizontal_even"), SchindlerLineaScreen2BlackHorizontalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_BLACK_HORIZONTAL_EVEN::get);
        SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_black_vertical_odd"), SchindlerLineaScreen2BlackVerticalOdd.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_ODD::get);
        SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_linea_screen_2_black_vertical_even"), SchindlerLineaScreen2BlackVerticalEven.BlockEntity::new, Blocks.SCHINDLER_LINEA_SCREEN_2_BLACK_VERTICAL_EVEN::get);
        SCHINDLER_FI_GS_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_button_1"), SchindlerFIGSButton1.BlockEntity::new, Blocks.SCHINDLER_FI_GS_BUTTON_1::get);
        SCHINDLER_FI_GS_TOUCH_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_touch_button_1"), SchindlerFIGSTouchButton1.BlockEntity::new, Blocks.SCHINDLER_FI_GS_TOUCH_BUTTON_1::get);
        SCHINDLER_FI_GS_TOUCH_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_touch_button_1_without_screen"), SchindlerFIGSTouchButton1WithoutScreen.BlockEntity::new, Blocks.SCHINDLER_FI_GS_TOUCH_BUTTON_1_WITHOUT_SCREEN::get);
        SCHINDLER_FI_GS_BUTTON_1_STEEL = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_button_1_steel"), SchindlerFIGSButton1Steel.BlockEntity::new, Blocks.SCHINDLER_FI_GS_BUTTON_1_STEEL::get);
        SCHINDLER_FI_GS_SCREEN_1_STEEL_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_steel_odd"), SchindlerFIGSScreen1SteelOdd.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_STEEL_ODD::get);
        SCHINDLER_FI_GS_SCREEN_1_STEEL_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_steel_even"), SchindlerFIGSScreen1SteelEven.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_STEEL_EVEN::get);
        SCHINDLER_FI_GS_SCREEN_1_BLACK_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_black_odd"), SchindlerFIGSScreen1BlackOdd.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_BLACK_ODD::get);
        SCHINDLER_FI_GS_SCREEN_1_BLACK_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_black_even"), SchindlerFIGSScreen1BlackEven.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_BLACK_EVEN::get);
        SCHINDLER_FI_GS_SCREEN_1_GREY_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_grey_odd"), SchindlerFIGSScreen1GreyOdd.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_GREY_ODD::get);
        SCHINDLER_FI_GS_SCREEN_1_GREY_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_fi_gs_screen_1_grey_even"), SchindlerFIGSScreen1GreyEven.BlockEntity::new, Blocks.SCHINDLER_FI_GS_SCREEN_1_GREY_EVEN::get);
        SCHINDLER_Z_LINE_3_KEYPAD_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_z_line_3_keypad_1"), SchindlerZLine3Keypad1.BlockEntity::new, Blocks.SCHINDLER_Z_LINE_3_KEYPAD_1::get);

        THYSSENKRUPP_TEGL1_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "thyssenkrupp_te_gl1_button_1"), ThyssenkruppTEGL1Button1.BlockEntity::new, Blocks.THYSSENKRUPP_TEGL1_BUTTON_1::get);

        HITACHI_VIB320_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib320_button_1"), HitachiVIB320Button.BlockEntity::new, Blocks.HITACHI_VIB320_BUTTON::get);
        HITACHI_VIB320_BUTTON_DOT_MATRIX = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib320_button_1_dot_matrix"), HitachiVIB320ButtonDotMatrix.BlockEntity::new, Blocks.HITACHI_VIB320_BUTTON_DOT_MATRIX::get);
        HITACHI_VIB320_BUTTON_HIP43 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib320_button_1_hip43"), HitachiVIB320ButtonHIP43.BlockEntity::new, Blocks.HITACHI_VIB320_BUTTON_HIP43::get);
        HITACHI_VIB322_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib322_button_1"), HitachiVIB322Button.BlockEntity::new, Blocks.HITACHI_VIB322_BUTTON::get);
        HITACHI_VIB322_BUTTON_DOT_MATRIX = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib322_button_1_dot_matrix"), HitachiVIB322ButtonDotMatrix.BlockEntity::new, Blocks.HITACHI_VIB322_BUTTON_DOT_MATRIX::get);
        HITACHI_VIB325_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib325_button_1"), HitachiVIB325Button.BlockEntity::new, Blocks.HITACHI_VIB325_BUTTON::get);
        HITACHI_VIB325_BUTTON_DOT_MATRIX = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib325_button_1_dot_matrix"), HitachiVIB325ButtonDotMatrix.BlockEntity::new, Blocks.HITACHI_VIB325_BUTTON_DOT_MATRIX::get);
        HITACHI_VIB221_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib221_button_1"), HitachiVIB221Button.BlockEntity::new, Blocks.HITACHI_VIB221_BUTTON::get);
        HITACHI_VIB221_BUTTON_DOT_MATRIX = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib221_button_1_dot_matrix"), HitachiVIB221ButtonDotMatrix.BlockEntity::new, Blocks.HITACHI_VIB221_BUTTON_DOT_MATRIX::get);
        HITACHI_VIB221_BUTTON_LCD_SEGMENTED = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib221_button_1_lcd_segmented"), HitachiVIB221ButtonLCDSegmented.BlockEntity::new, Blocks.HITACHI_VIB221_BUTTON_LCD_SEGMENTED::get);
        HITACHI_VIB221_BUTTON_HIP43 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib221_button_1_hip43"), HitachiVIB221ButtonHIP43.BlockEntity::new, Blocks.HITACHI_VIB221_BUTTON_HIP43::get);
        HITACHI_VIB820_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib820_button_1"), HitachiVIB820Button.BlockEntity::new, Blocks.HITACHI_VIB820_BUTTON::get);
        HITACHI_VIB820_BUTTON_LCD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib820_button_1_lcd"), HitachiVIB820ButtonLCD.BlockEntity::new, Blocks.HITACHI_VIB820_BUTTON_LCD::get);
        HITACHI_VIB68_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib68_button_1"), HitachiVIB68Button.BlockEntity::new, Blocks.HITACHI_VIB68_BUTTON::get);
        HITACHI_VIB191_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib191_button_1"), HitachiVIB191Button.BlockEntity::new, Blocks.HITACHI_VIB191_BUTTON::get);
        HITACHI_VIB192_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib192_button_1"), HitachiVIB192Button.BlockEntity::new, Blocks.HITACHI_VIB192_BUTTON::get);
        HITACHI_HB820_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hb820_button_1"), HitachiHB820Button.BlockEntity::new, Blocks.HITACHI_HB820_BUTTON::get);
        HITACHI_HSB820_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hsb820_button_1"), HitachiHSB820Button.BlockEntity::new, Blocks.HITACHI_HSB820_BUTTON::get);
        HITACHI_GHL820_LANTERN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl820_lantern_1_odd"), HitachiGHL820Lantern1Odd.BlockEntity::new, Blocks.HITACHI_GHL820_LANTERN_ODD::get);
        HITACHI_GHL820_LANTERN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl820_lantern_1_even"), HitachiGHL820Lantern1Even.BlockEntity::new, Blocks.HITACHI_GHL820_LANTERN_EVEN::get);
        HITACHI_GHL668_LANTERN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl668_lantern_1_odd"), HitachiGHL668Lantern1Odd.BlockEntity::new, Blocks.HITACHI_GHL668_LANTERN_ODD::get);
        HITACHI_GHL668_LANTERN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl668_lantern_1_even"), HitachiGHL668Lantern1Even.BlockEntity::new, Blocks.HITACHI_GHL668_LANTERN_EVEN::get);
        HITACHI_GHL673_LANTERN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl673_lantern_1_odd"), HitachiGHL673Lantern1Odd.BlockEntity::new, Blocks.HITACHI_GHL673_LANTERN_ODD::get);
        HITACHI_GHL673_LANTERN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghl673_lantern_1_even"), HitachiGHL673Lantern1Even.BlockEntity::new, Blocks.HITACHI_GHL673_LANTERN_EVEN::get);
        HITACHI_GHI675_SCREEN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghi675_screen_1_odd"), HitachiGHI675Screen1Odd.BlockEntity::new, Blocks.HITACHI_GHI675_SCREEN_ODD::get);
        HITACHI_GHI675_SCREEN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghi675_screen_1_even"), HitachiGHI675Screen1Even.BlockEntity::new, Blocks.HITACHI_GHI675_SCREEN_EVEN::get);
        HITACHI_VIB820PRO_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib820pro_button_1"), HitachiVIB820proButton.BlockEntity::new, Blocks.HITACHI_VIB820PRO_BUTTON::get);
        HITACHI_HSB820PRO_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hsb820pro_button_1"), HitachiHSB820proButton.BlockEntity::new, Blocks.HITACHI_HSB820PRO_BUTTON::get);
        HITACHI_GHD820PRO_SCREEN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghd820pro_screen_1_odd"), HitachiGHD820proScreen1Odd.BlockEntity::new, Blocks.HITACHI_GHD820PRO_SCREEN_ODD::get);
        HITACHI_GHD820PRO_SCREEN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_ghd820pro_screen_1_even"), HitachiGHD820proScreen1Even.BlockEntity::new, Blocks.HITACHI_GHD820PRO_SCREEN_EVEN::get);
        HITACHI_VIB628_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib628_button_1"), HitachiVIB628Button.BlockEntity::new, Blocks.HITACHI_VIB628_BUTTON::get);
        HITACHI_HB628_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hb628_button_1"), HitachiHB628Button.BlockEntity::new, Blocks.HITACHI_HB628_BUTTON::get);
        HITACHI_VIB668_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib668_button_1"), HitachiVIB668Button.BlockEntity::new, Blocks.HITACHI_VIB668_BUTTON::get);
        HITACHI_VIB658_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib658_button_1"), HitachiVIB658Button.BlockEntity::new, Blocks.HITACHI_VIB658_BUTTON::get);
        HITACHI_HB658_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hb658_button_1"), HitachiHB658Button.BlockEntity::new, Blocks.HITACHI_HB658_BUTTON::get);
        HITACHI_VIB663_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib663_button_1"), HitachiVIB663Button.BlockEntity::new, Blocks.HITACHI_VIB663_BUTTON::get);
        HITACHI_VIB681_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib681_button_1"), HitachiVIB681Button.BlockEntity::new, Blocks.HITACHI_VIB681_BUTTON::get);
        HITACHI_VIB676_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib676_button_1"), HitachiVIB676Button.BlockEntity::new, Blocks.HITACHI_VIB676_BUTTON::get);
        HITACHI_VIB679_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib679_button_1"), HitachiVIB679Button.BlockEntity::new, Blocks.HITACHI_VIB679_BUTTON::get);
        HITACHI_VIB673_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib673_button_1"), HitachiVIB673Button.BlockEntity::new, Blocks.HITACHI_VIB673_BUTTON::get);
        HITACHI_VIB673_BUTTON_HIP43 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib673_button_1_hip43"), HitachiVIB673ButtonHIP43.BlockEntity::new, Blocks.HITACHI_VIB673_BUTTON_HIP43::get);
        HITACHI_HB673_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hb673_button_1"), HitachiHB673Button.BlockEntity::new, Blocks.HITACHI_HB673_BUTTON::get);
        HITACHI_VIB181A_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib181a_button_1"), HitachiVIB181AButton.BlockEntity::new, Blocks.HITACHI_VIB181A_BUTTON::get);
        HITACHI_VIB182A_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_vib182a_button_1"), HitachiVIB182AButton.BlockEntity::new, Blocks.HITACHI_VIB182A_BUTTON::get);
        HITACHI_HB181A_BUTTON = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_hb181a_button_1"), HitachiHB181AButton.BlockEntity::new, Blocks.HITACHI_HB181A_BUTTON::get);
        HITACHI_B85_BUTTON_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_b85_button_1"), HitachiB85Button1.BlockEntity::new, Blocks.HITACHI_B85_BUTTON_1::get);
        HITACHI_B85_BUTTON_1_WITHOUT_SCREEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_b85_button_1_without_screen"), HitachiB85Button1WithoutScreen.BlockEntity::new, Blocks.HITACHI_B85_BUTTON_1_WITHOUT_SCREEN::get);
        HITACHI_B85_BUTTON_2 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_b85_button_2"), HitachiB85Button2.BlockEntity::new, Blocks.HITACHI_B85_BUTTON_2::get);
        HITACHI_BUTTON_PAFC = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_button_pafc"), HitachiButtonPAFC.BlockEntity::new, Blocks.HITACHI_BUTTON_PAFC::get);

        TONIC_DS_SCREEN_1_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_ds_screen_1_odd"), TonicDSScreen1Odd.BlockEntity::new, Blocks.TONIC_DS_SCREEN_1_ODD::get);
        TONIC_DS_SCREEN_1_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_ds_screen_1_even"), TonicDSScreen1Even.BlockEntity::new, Blocks.TONIC_DS_SCREEN_1_EVEN::get);
        TONIC_DM_SCREEN_1_RED_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_red_odd"), TonicDMScreen1RedOdd.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_RED_ODD::get);
        TONIC_DM_SCREEN_1_RED_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_red_even"), TonicDMScreen1RedEven.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_RED_EVEN::get);
        TONIC_DM_SCREEN_1_GREEN_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_green_odd"), TonicDMScreen1GreenOdd.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_GREEN_ODD::get);
        TONIC_DM_SCREEN_1_GREEN_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_green_even"), TonicDMScreen1GreenEven.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_GREEN_EVEN::get);
        TONIC_DM_SCREEN_1_YELLOW_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_yellow_odd"), TonicDMScreen1YellowOdd.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_YELLOW_ODD::get);
        TONIC_DM_SCREEN_1_YELLOW_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "tonic_dm_screen_1_yellow_even"), TonicDMScreen1YellowEven.BlockEntity::new, Blocks.TONIC_DM_SCREEN_1_YELLOW_EVEN::get);

        HITACHI_B85_DOOR_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "hitachi_b85_door_1"), HitachiB85Door1.BlockEntity::new, Blocks.HITACHI_B85_DOOR_1::get);
        KONE_M_DOOR_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "kone_m_door_1"), KoneMDoor1.BlockEntity::new, Blocks.KONE_M_DOOR_1::get);
        MITSUBISHI_NEXWAY_DOOR_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "mitsubishi_nexway_door_1"), MitsubishiNexWayDoor1.BlockEntity::new, Blocks.MITSUBISHI_NEXWAY_DOOR_1::get);
        OTIS_E411_US_DOOR_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "otis_e411_us_door_1"), OtisE411USDoor1.BlockEntity::new, Blocks.OTIS_E411_US_DOOR_1::get);
        SCHINDLER_QKS9_DOOR_1 = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "schindler_qks9_door_1"), SchindlerQKS9Door1.BlockEntity::new, Blocks.SCHINDLER_QKS9_DOOR_1::get);

        PAT_RS01_RAILWAY_SIGN_2_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_2_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(2, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_2_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_2_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_2_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(2, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_2_ODD::get);
        PAT_RS01_RAILWAY_SIGN_3_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_3_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(3, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_3_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_3_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_3_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(3, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_3_ODD::get);
        PAT_RS01_RAILWAY_SIGN_4_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_4_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(4, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_4_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_4_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_4_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(4, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_4_ODD::get);
        PAT_RS01_RAILWAY_SIGN_5_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_5_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(5, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_5_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_5_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_5_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(5, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_5_ODD::get);
        PAT_RS01_RAILWAY_SIGN_6_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_6_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(6, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_6_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_6_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_6_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(6, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_6_ODD::get);
        PAT_RS01_RAILWAY_SIGN_7_EVEN = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_7_even"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(7, false, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_7_EVEN::get);
        PAT_RS01_RAILWAY_SIGN_7_ODD = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "pat_rs01_railway_sign_7_odd"), (pos, state) -> new PATRS01RailwaySign.BlockEntity(7, true, pos, state), Blocks.PAT_RS01_RAILWAY_SIGN_7_ODD::get);

        LIFT_TRACK_EMPTY_FLOOR = Init.REGISTRY.registerBlockEntityType(new Identifier(Init.MOD_ID, "lift_track_empty_floor"), EmptyFloor.BlockEntity::new, Blocks.LIFT_TRACK_EMPTY_FLOOR::get);

    }

    public static void init() {
        Init.LOGGER.info("正在注册方块实体");
    }
}