name: Build
on: [ pull_request, push ,workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.4, 1.20.1, 1.20.4 ]
    #runs-on: self-hosted
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup Fabric files
        run: ./gradlew fabric:setupFiles -PminecraftVersion="${{ matrix.minecraft }}"
      - name: Setup Forge files
        run: ./gradlew forge:setupFiles -PminecraftVersion="${{ matrix.minecraft }}"
      - name: Build ${{ matrix.minecraft }}
        run: ./gradlew build -PminecraftVersion="${{ matrix.minecraft }}" --no-daemon
      - name: Capture release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Fabric and Forge ${{ matrix.minecraft }}
          path: build/release/
